### ISSUE TITLE
Device --> Settings - Can not save -- Broken

### ISSUE THREAD

**Issue by flyer292** [fusionpbx/fusionpbx#1959]
After one of the last updates (sometime in the past week)
When you edit a device configuration and change the Settings value or add a new one to settings and click save the changes are not saved and you get a blank page

**Comment by flyer292** [comment]
I am also seeing the same type of issue with the IVR menu  Can not save new entries

**Comment by blakepriddy** [comment]
I am seeing the same thing on Ring Groups.

**Comment by flyer292** [comment]
Seems to be a few different places that are currently broken.  Destinations as well

**Comment by markjcrane** [comment]
Master branch I have been doing some changes. Ring groups are fixed IVR Menu should be fixed. Dialplan Destinations as well has been fixed.

**Comment by markjcrane** [comment]
Device edit should be fixed as of last night.

**Comment by markjcrane** [comment]
Changes were necessary to make a new transaction log for user audit feature.

**Comment by kt4vqkt4vq** [comment]
Hi Mark, couple issues that sounds like this last update fixes just want to make sure.  Had RingGroup that did not work so I removed the RG and rebuilt it.  It does not appear in GUI and does not work.  Als IVR on invlaid entry will go back the the main greeting but regardless of the qty of mis-dials it always goes to Main greeting and never anywhere else.  The zero out option is going someplace other than what is set in the GUI.

Does this fix that?

**Comment by flyer292** [comment]
All of the issues for me now appear to be fixed... thanks

**Comment by flyer292** [comment]
Appears that there is still an outstanding issue with Fax.  When you save it, it removes the entry from the dialplan manager

**Comment by markjcrane** [comment]
Fax should be fixed now please test.

**Comment by flyer292** [comment]
This is now fixed.. thanks

**Comment by flyer292** [comment]
Sorry... I think I found one more that needs to be updated
Call Center, same problem as the other

**Comment by markjcrane** [comment]
I updated call center already.

Mark

**Comment by flyer292** [comment]
I have doubled checked that I ran the updated and also set defaults etc, but same thing, when you create a new call center it is not being added to the dialplan manager like before and the call just hangs up for new call centers created

**Comment by markjcrane** [comment]
Did you run upgrade -> schema? I found when working on it I was missing a field that was needed.

**Comment by flyer292** [comment]
I always run that after each upgrade
Scheme, Data Types & App Defaults

Just did them again same results

**Comment by markjcrane** [comment]
I was able to duplicate the problem with Call Center and then fixed it.

**Comment by markjcrane** [comment]
Fixed device profiles too.

**Comment by flyer292** [comment]
Call Center now creates a rule under dialplan manger, when you look at the new rule it does not have any tags or types etc below the dialplan (same as fax now) not sure if this is intended or not
Call Center still appears to have something wrong.  It is going directly to the Tiumeout action even through agents are available
Also noticed when you edit an existing agent in the Call Center Queue (Change tier position etc) it does save but takes you to a blank screen

**Comment by markjcrane** [comment]
Blank screen means there was an error which you can see by looking at nginx logs to see it.

**Comment by markjcrane** [comment]
"Also noticed when you edit an existing agent in the Call Center Queue (Change tier position etc) it does save but takes you to a blank screen"

Tested this and its working fine.
